version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /benchmark
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/plugins
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/seroval
    schedule:
      interval: daily
