// Used for mapping isomorphic references
export const REFERENCES_KEY = '__SEROVAL_REFS__';

export const GLOBAL_CONTEXT_KEY = '__SEROVAL__';

export const GLOBAL_CONTEXT_REFERENCES = 'r';

export const GLOBAL_CONTEXT_RESOLVERS = 's';

export const GLOBAL_CONTEXT_REJECTERS = 'f';

export const GLOBAL_CONTEXT_PROMISE_CONSTRUCTOR = 'p';

export const ROOT_REFERENCE = 'o';

export const GLOBAL_CONTEXT_PROPERTIES = [
  GLOBAL_CONTEXT_REFERENCES,
  GLOBAL_CONTEXT_PROMISE_CONSTRUCTOR,
  GLOBAL_CONTEXT_RESOLVERS,
  GLOBAL_CONTEXT_REJECTERS,
];

export const CROSS_IIFE_PARAMS = GLOBAL_CONTEXT_PROPERTIES.join(',');

export const CROSS_IIFE_ARGUMENTS = `(${GLOBAL_CONTEXT_PROPERTIES.map((item) => `${GLOBAL_CONTEXT_KEY}.${item}`).join(',')})`;
