export const enum SerovalBinaryType {
  Preamble = 0,
  Root = 1,
  Constant = 2,
  Number = 3,
  String = 4,
  BigInt = 5,
  WKSymbol = 6,
  ObjectAssign = 7,
  ArrayAssign = 8,
  ObjectFlag = 9,
  Array = 10,
  Stream = 11,
  StreamNext = 12,
  StreamThrow = 13,
  StreamReturn = 14,
  Sequence = 15,
  SequencePush = 16,
  Plugin = 17,
  Object = 18,
  NullConstructor = 19,
  Date = 20,
  Error = 21,
  Boxed = 22,
  ArrayBuffer = 23,
  TypedArray = 24,
  BigIntTypedArray = 25,
  DataView = 26,
  Map = 27,
  MapSet = 28,
  Set = 29,
  SetAdd = 30,
  Promise = 31,
  PromiseSuccess = 32,
  PromiseFailure = 33,
  RegExp = 34,
  AggregateError = 35,
  Iterator = 36,
  AsyncIterator = 37,
  Pending = 38,
  Temporal = 39,
  Reference = 40,
}

export const NODE_TYPE_NAME: Record<SerovalBinaryType, string> = {
  [SerovalBinaryType.Preamble]: 'Preamble',
  [SerovalBinaryType.Root]: 'Root',
  [SerovalBinaryType.Constant]: 'Constant',
  [SerovalBinaryType.Number]: 'Number',
  [SerovalBinaryType.String]: 'String',
  [SerovalBinaryType.BigInt]: 'BigInt',
  [SerovalBinaryType.WKSymbol]: 'WKSymbol',
  [SerovalBinaryType.ObjectAssign]: 'ObjectAssign',
  [SerovalBinaryType.ArrayAssign]: 'ArrayAssign',
  [SerovalBinaryType.ObjectFlag]: 'ObjectFlag',
  [SerovalBinaryType.Array]: 'Array',
  [SerovalBinaryType.Stream]: 'Stream',
  [SerovalBinaryType.StreamNext]: 'StreamNext',
  [SerovalBinaryType.StreamThrow]: 'StreamThrow',
  [SerovalBinaryType.StreamReturn]: 'StreamReturn',
  [SerovalBinaryType.Sequence]: 'Sequence',
  [SerovalBinaryType.SequencePush]: 'SequencePush',
  [SerovalBinaryType.Plugin]: 'Plugin',
  [SerovalBinaryType.Object]: 'Object',
  [SerovalBinaryType.NullConstructor]: 'NullConstructor',
  [SerovalBinaryType.Date]: 'Date',
  [SerovalBinaryType.Error]: 'Error',
  [SerovalBinaryType.Boxed]: 'Boxed',
  [SerovalBinaryType.ArrayBuffer]: 'ArrayBuffer',
  [SerovalBinaryType.TypedArray]: 'TypedArray',
  [SerovalBinaryType.BigIntTypedArray]: 'BigIntTypedArray',
  [SerovalBinaryType.DataView]: 'DataView',
  [SerovalBinaryType.Map]: 'Map',
  [SerovalBinaryType.MapSet]: 'MapSet',
  [SerovalBinaryType.Set]: 'Set',
  [SerovalBinaryType.SetAdd]: 'SetAdd',
  [SerovalBinaryType.Promise]: 'Promise',
  [SerovalBinaryType.PromiseSuccess]: 'PromiseSuccess',
  [SerovalBinaryType.PromiseFailure]: 'PromiseFailure',
  [SerovalBinaryType.RegExp]: 'RegExp',
  [SerovalBinaryType.AggregateError]: 'AggregateError',
  [SerovalBinaryType.Iterator]: 'Iterator',
  [SerovalBinaryType.AsyncIterator]: 'AsyncIterator',
  [SerovalBinaryType.Pending]: 'Pending',
  [SerovalBinaryType.Temporal]: 'Temporal',
  [SerovalBinaryType.Reference]: 'Reference',
};

export const enum SerovalEndianness {
  LE = 1,
  BE = 2,
}
